#!/bin/sh

cd "$(dirname "$0")"

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 name /path/to/project"
    exit 1
fi

if ! [[ "$2" =~ ^/ ]]; then
    echo "Relative paths cannot be specified: $2"
    exit 1
fi

if [ -d $2 ]; then
    echo "Directory $2 already exist."
    exit 1
fi

echo "Create directory: $2"
mkdir -p "$2"

echo "Create directory: $2/src"
mkdir "$2/src"

echo "Create directory: $2/bmp"
mkdir "$2/bmp"

echo "Create directory: $2/vgm"
mkdir "$2/vgm"

echo "Create directory: $2/wav"
mkdir "$2/wav"

echo "Create file: $2/.clang-format"
cp -p template/clang-format "$2/.clang-format"

echo "Create file: $2/.gitignore"
cp -p template/gitignore "$2/.gitignore"

echo "Create file: $2/Makefile"
cp -p template/Makefile "$2/Makefile"

echo "Create file: $2/README.md"
echo "# $1" > "$2/README.md"

echo "Create file: $2/src/main.c"
cp -p template/main.c "$2/src/main.c"

echo "Create file: $2/bmp/font.bmp"
cp -p template/font.bmp "$2/bmp/font.bmp"

echo "Create file: $2/vgm/sample.vgm"
cp -p template/sample.vgm "$2/vgm/sample.vgm"

echo "Create file: $2/wav/sample.wav"
cp -p template/sample.wav "$2/wav/sample.wav"

echo "Create file: $2/LICENSE-Musashi.txt"
cp -p ../../LICENSE-Musashi.txt "$2/LICENSE-Musashi.txt"

echo "Create file: $2/LICENSE-ymfm.txt"
cp -p ../../LICENSE-ymfm.txt "$2/LICENSE-ymfm.txt"

echo "Create file: $2/LICENSE-VGSX.txt"
cp -p ../../LICENSE-VGSX.txt "$2/LICENSE-VGSX.txt"

echo "Setup git"
cd "$2"
git init
git branch -M master

echo "Setup gitsubmodule"
git submodule add https://github.com/suzukiplan/vgsx
git add -A
git commit -m "Initial commit (empty VGS-X project)"

echo "Try first build."
make

echo "$1 carted at: $2"
