all:
	cd sdl2 && make
	cd bmp2chr && make
	cd bmp2img && make
	cd bmp2pal && make
	cd csv2var && make
	cd makerom && make
	cd bin2var && make
	cd vgm2wav && make

clean:
	cd sdl2 && make clean
	cd bmp2chr && make clean
	cd bmp2img && make clean
	cd bmp2pal && make clean
	cd csv2var && make clean
	cd makerom && make clean
	cd bin2var && make clean
	cd vgm2wav && make clean
